# Generated by Django 4.2.4 on 2024-06-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondereception',
            name='facture',
        ),
    ]
