# Generated by Django 4.2.4 on 2024-06-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0004_bondereception_bondereceptionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondereceptionitem',
            name='bon_de_reception',
        ),
        migrations.DeleteModel(
            name='BonDeReception',
        ),
        migrations.DeleteModel(
            name='BonDeReceptionItem',
        ),
    ]
